# Generated by Django 3.1.7 on 2021-02-26 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TwitterData',
            fields=[
                ('id', models.PositiveIntegerField(max_length=30, primary_key=True, serialize=False, unique=True)),
                ('text', models.CharField(max_length=4000)),
                ('user', models.CharField(max_length=100)),
                ('lang', models.CharField(max_length=10)),
            ],
        ),
    ]
