# Generated by Django 3.1.7 on 2021-02-26 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0003_auto_20210226_2327'),
    ]

    operations = [
        migrations.AlterField(
            model_name='twitterdata',
            name='url',
            field=models.URLField(default=None),
        ),
    ]
