# Generated by Django 3.1.7 on 2021-02-26 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0004_auto_20210226_2329'),
    ]

    operations = [
        migrations.AlterField(
            model_name='twitterdata',
            name='url',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
